/*                       Types of Events

         Events are of 2 types:

1.  Semantic events: These are generated by "software components" like Button, Frame etc.

2. Low-level events: These are generated by "hardware components" like mouse and keyboard etc.

                              Mouse events

Mouse events can be handled by two listeners:

a) MouseListener when mouse is stable. This listener includes 5 abstract methods for 5 different mouse actions.

b) MouseMotionListener when the mouse is in motion. This listener includes 2 abstract methods for 2 different mouse movements.

*/

// to change the background of the frame as per the action using MouseListener.

import java.awt.*;
import java.awt.event.*;

public class MouseDemo extends Frame implements MouseListener
{
    public MouseDemo( )
    {
                               // link the frame with ML
            addMouseListener(this);

             // shortcut for window closing 

 addWindowListener(new WindowAdapter( )
  { 
    public void windowClosing(WindowEvent e)
    {
          System.exit(0);
    }
  }
  );
            setSize(300,300);
            setVisible(true);
    }

    // override the 5 abstract methods of ML 

   public void mousePressed(MouseEvent e)
   {
      // do some action to distinguish from other methods
          setBackground(Color.red);
          System.out.println("Mouse is Pressed");
   }
  public void mouseReleased(MouseEvent e)
   {
          setBackground(Color.blue);
   System.out.println("Mouse is Released");   
   }
   public void mouseClicked(MouseEvent e)
   {
          setBackground(Color.green);
     System.out.println("Mouse is Clicked");
   }
   public void mouseEntered(MouseEvent e)
   {
          setBackground(Color.cyan);
          System.out.println("Mouse is Entered");
   }
  public void mouseExited(MouseEvent e)
  {
          setBackground(Color.magenta);
          System.out.println("Mouse is Exited");
   }
   public static void main(String args[])
   {
       new MouseDemo();
   }
}
